#!/usr/bin/env python3
"""Split a total three-element Windkessel across the outlets by outlet area.

The whole distal bed is described by one proximal resistance, one distal
resistance and one compliance. Each outlet is given the fraction

    f_i = A_i^(k/2) / sum_j A_j^(k/2)

of the total flow, where A_i is the outlet area and k the exponent of the flow
split Q_i ~ r_i^k: k = 2 is the area rule (Q proportional to area), k = 3 is
Murray's law. Outlet i then gets

    Rch_i = Rp / f_i,    R_i = Rd / f_i,    C_i = C * f_i

so the outlets in parallel reproduce the totals exactly, and every outlet keeps
the time constant R_i C_i = Rd C of the whole bed. Only area ratios are used,
so the areas may be in any unit.

The result is written as a dictionary fragment of per-outlet patch entries,
which the template's 0/fluid/p includes. Explicit patch names take precedence
over the template's "outlet.*" entry, which remains as a fallback.
"""

from __future__ import annotations

import argparse
import csv
import math
import re
import sys
from pathlib import Path


RHO = re.compile(r"(?m)^[ \t]*rho\b[^;]*?(?P<value>[0-9.eE+-]+)[ \t]*;")


def positive_float(value: str) -> float:
    number = float(value)
    if not math.isfinite(number) or number <= 0.0:
        raise argparse.ArgumentTypeError("must be finite and greater than 0")
    return number


def read_outlet_areas(filename: Path) -> list[tuple[str, float]]:
    with filename.open(newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        missing = {"area", "name"} - set(reader.fieldnames or ())
        if missing:
            raise RuntimeError(
                f"profile CSV is missing columns: {', '.join(sorted(missing))}; "
                "regenerate it with the current pulmonary_centerlines.py"
            )
        outlets = []
        for row in reader:
            if not row["name"].startswith("outlet"):
                continue
            area = float(row["area"])
            if not math.isfinite(area) or area <= 0.0:
                raise RuntimeError(f"{row['name']} has a non-positive area: {area}")
            outlets.append((row["name"], area))
    if not outlets:
        raise RuntimeError(f"no outlet rows found in {filename}")
    # Natural order (outlet2 before outlet10) keeps the file easy to read.
    outlets.sort(key=lambda item: int(re.sub(r"\D", "", item[0]) or 0))
    return outlets


def read_density(filename: Path | None, default: float) -> float:
    if filename is None or not filename.is_file():
        return default
    match = RHO.search(filename.read_text(encoding="utf-8"))
    return float(match.group("value")) if match else default


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("profiles_csv", type=Path)
    parser.add_argument("output", type=Path, help="dictionary fragment to write")
    parser.add_argument(
        "--proximal-resistance", type=positive_float, default=3.3e6,
        help="total proximal (characteristic) resistance Rp [Pa s/m^3] (default: 3.3e6)",
    )
    parser.add_argument(
        "--distal-resistance", type=positive_float, default=2.0e7,
        help="total distal resistance Rd [Pa s/m^3] (default: 2e7)",
    )
    parser.add_argument(
        "--compliance", type=positive_float, default=3.5e-8,
        help="total compliance C [m^3/Pa] (default: 3.5e-8)",
    )
    parser.add_argument(
        "--exponent", type=positive_float, default=2.0,
        help="flow-split exponent k in Q ~ r^k: 2 area rule, 3 Murray (default: 2)",
    )
    parser.add_argument(
        "--transport-properties", type=Path,
        help="read rho from this transportProperties instead of --rho",
    )
    parser.add_argument(
        "--rho", type=positive_float, default=1060.0,
        help="fluid density used by windkesselPressure (default: 1060)",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    profiles_csv = args.profiles_csv.expanduser().resolve()
    if not profiles_csv.is_file():
        raise FileNotFoundError(profiles_csv)

    outlets = read_outlet_areas(profiles_csv)
    rho = read_density(args.transport_properties, args.rho)
    weights = [area ** (args.exponent / 2.0) for _, area in outlets]
    total_weight = sum(weights)

    lines = [
        "// Generated by pythonScripts/windkessel_outlets.py; edit the totals",
        "// and rerun rather than editing these entries by hand.",
        f"//   Rp = {args.proximal_resistance:g} Pa s/m^3, "
        f"Rd = {args.distal_resistance:g} Pa s/m^3, C = {args.compliance:g} m^3/Pa",
        f"//   flow split Q ~ r^{args.exponent:g}, rho = {rho:g}",
        "",
    ]
    print(f"{'Outlet':<10} {'flow fraction':>13} {'Rch':>12} {'R':>12} {'C':>12}")
    for (name, _), weight in zip(outlets, weights):
        fraction = weight / total_weight
        rch = args.proximal_resistance / fraction
        r = args.distal_resistance / fraction
        c = args.compliance * fraction
        print(f"{name:<10} {fraction:>13.4f} {rch:>12.4g} {r:>12.4g} {c:>12.4g}")
        lines += [
            f"{name}",
            "{",
            "    type        windkesselPressure;",
            f"    // flow fraction {fraction:.6f}",
            f"    R           {r:.6g};",
            f"    Rch         {rch:.6g};",
            f"    C           {c:.6g};",
            f"    rho         {rho:g};",
            "    value       uniform 0;",
            "}",
            "",
        ]

    output = args.output.expanduser()
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {len(outlets)} Windkessel outlet(s) to {output}")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except (OSError, RuntimeError, ValueError) as error:
        print(f"Error: {error}", file=sys.stderr)
        sys.exit(1)
