#!/usr/bin/env bash

# Stop on a failed command (-e), an unset variable (-u), or a failed command
# inside a pipeline (pipefail). This prevents the workflow continuing with
# missing or incomplete geometry.
set -euo pipefail

# Find the directory containing this script, even when meshing.sh is launched
# from another working directory. BASH_SOURCE[0] is the path to this file.
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

# Construct an absolute path to the Python geometry-processing script.
CENTERLINE_SCRIPT="$SCRIPT_DIR/pythonScripts/pulmonary_centerlines.py"
CSV_SCRIPT="$SCRIPT_DIR/pythonScripts/centerlines_to_csv.py"
GAUSS_SCRIPT="$SCRIPT_DIR/pythonScripts/Gauss.py"
EMPTY_PATCH_SCRIPT="$SCRIPT_DIR/pythonScripts/add_empty_boundary_patch.py"
REFINEMENT_SCRIPT="$SCRIPT_DIR/pythonScripts/add_refinements.py"
TEMPLATE_MESH_DIR="$SCRIPT_DIR/templateMesh"
TEMPLATE_CASE_DIR="$SCRIPT_DIR/templateCase"
RUN_DIR="$SCRIPT_DIR/run"

# Allow an alternate cfMesh installation to be selected on systems where the
# utility is not on PATH.
SURFACE_FEATURE_EDGES="${SURFACE_FEATURE_EDGES:-surfaceFeatureEdges}"
CARTESIAN_MESH="${CARTESIAN_MESH:-cartesianMesh}"
CHECK_MESH="${CHECK_MESH:-checkMesh}"
MAP_EXTRUDE_DISTANCE="${MAP_EXTRUDE_DISTANCE:-mapExtrudeDistance}"
AUTO_PATCH="${AUTO_PATCH:-autoPatch}"
FOAM_LIST_TIMES="${FOAM_LIST_TIMES:-foamListTimes}"
CREATE_PATCH="${CREATE_PATCH:-createPatch}"
VAR_EXTRUDE_MESH="${VAR_EXTRUDE_MESH:-varExtrudeMesh}"

# Use the repository's fsi-env Python by default. If an HPC user stores the
# environment elsewhere, an existing FSI_PYTHON environment variable overrides
# this default; for example: export FSI_PYTHON=/project/fsi-env/bin/python.
FSI_PYTHON="${FSI_PYTHON:-$SCRIPT_DIR/.env/fsi-env/bin/python}"

# Fail early with an actionable message if the selected Python is absent or is
# not executable. The -x test checks both existence and execute permission.
if [[ ! -x "$FSI_PYTHON" ]]; then
    cat >&2 <<EOF
Error: the FSI Python executable was not found:
  $FSI_PYTHON

Set FSI_PYTHON to the Python executable in an environment containing VTK and
VMTK, for example:
  export FSI_PYTHON=/path/to/fsi-env/bin/python
EOF
    exit 1
fi

# Fail before processing if the repository's Python script is missing.
if [[ ! -f "$CENTERLINE_SCRIPT" ]]; then
    echo "Error: centerline script not found: $CENTERLINE_SCRIPT" >&2
    exit 1
fi

# The CSV exporter runs immediately after successful centerline extraction.
if [[ ! -f "$CSV_SCRIPT" ]]; then
    echo "Error: CSV export script not found: $CSV_SCRIPT" >&2
    exit 1
fi

# Gauss.py maps smoothed centerline diameters and the requested wall thickness
# onto the uncapped surface generated by the first stage.
if [[ ! -f "$GAUSS_SCRIPT" ]]; then
    echo "Error: Gaussian thickness script not found: $GAUSS_SCRIPT" >&2
    exit 1
fi

if [[ ! -f "$EMPTY_PATCH_SCRIPT" ]]; then
    echo "Error: empty boundary patch script not found: $EMPTY_PATCH_SCRIPT" >&2
    exit 1
fi

if [[ ! -f "$REFINEMENT_SCRIPT" ]]; then
    echo "Error: refinement script not found: $REFINEMENT_SCRIPT" >&2
    exit 1
fi

if [[ ! -d "$TEMPLATE_MESH_DIR" ]]; then
    echo "Error: mesh template directory not found: $TEMPLATE_MESH_DIR" >&2
    exit 1
fi

if [[ ! -d "$TEMPLATE_CASE_DIR" ]]; then
    echo "Error: case template directory not found: $TEMPLATE_CASE_DIR" >&2
    exit 1
fi

if ! command -v "$SURFACE_FEATURE_EDGES" >/dev/null 2>&1; then
    echo "Error: surfaceFeatureEdges executable not found: $SURFACE_FEATURE_EDGES" >&2
    exit 1
fi

for required_utility in \
    "$CARTESIAN_MESH" "$CHECK_MESH" "$MAP_EXTRUDE_DISTANCE" \
    "$AUTO_PATCH" "$FOAM_LIST_TIMES" "$CREATE_PATCH" \
    "$VAR_EXTRUDE_MESH"; do
    if ! command -v "$required_utility" >/dev/null 2>&1; then
        echo "Error: required meshing utility not found: $required_utility" >&2
        exit 1
    fi
done

# Run one meshing utility inside its case directory with all of its output
# captured in a log file, printing only a short description of the step. The
# log is named in the error message so a failure can still be diagnosed.
run_step() {
    local description="$1" work_dir="$2" log_name="$3"
    shift 3
    echo "$description"
    if ! ( cd "$work_dir" && "$@" > "$log_name" 2>&1 ); then
        echo "Error: step failed: $description" >&2
        echo "See $work_dir/$log_name" >&2
        exit 1
    fi
}

# At least the input STL positional argument is required. Exit status 2 denotes
# invalid command-line usage.
if [[ $# -eq 0 ]]; then
    echo "Usage: $0 INPUT.stl [--gaussian-sigma VALUE] [--extrusion-percentage VALUE]" >&2
    echo "       [--output-dir DIR] [--prefix NAME] [--skip-centerlines]" >&2
    echo "       [--smoothing-iterations N] [--smoothing-passband VALUE]" >&2
    echo "       [--extension-diameters VALUE] [--no-saddle-smoothing]" >&2
    echo "       [--saddle-safety-factor VALUE] [--saddle-target-radius VALUE]" >&2
    echo "       [--saddle-dilation N] [--cells-per-radius VALUE]" >&2
    echo "       [--sphere-radius-factor VALUE]" >&2
    echo "       [--thickness-smoothing-passes N] [--refine-narrow-vessels]" >&2
    echo "       [--max-mapping-distance VALUE]" >&2
    exit 2
fi

# Copy every command-line argument into an array. Using an array preserves
# spaces and special characters in paths when the arguments are forwarded.
arguments=("$@")

# Derive the default output prefix from the STL filename. These values are also
# used below to identify the exact centerline VTP produced by the Python step.
input_name="$(basename -- "$1")"
case_name="${input_name%.*}"
output_prefix="$case_name"
output_dir=""
skip_centerlines=false
gaussian_sigma=""
extrusion_percentage=""
cells_per_radius="3.0"
sphere_radius_factor="4.0"
thickness_smoothing_passes="10"
refine_narrow_vessels=false
# mapExtrudeDistance aborts if any wall point is further than this from the
# thickness-map surface. Its own default of 0.2 is far tighter than a 1 mm mesh
# warrants: cfMesh snapping leaves a handful of rim points a few tenths of a
# millimetre out, which is harmless because the thickness field is smooth there.
# This stays small enough to still catch a units or geometry mismatch.
max_mapping_distance="1.0"

# Read the output-related options without removing them from the array that is
# passed to pulmonary_centerlines.py. Both --option value and --option=value
# forms are supported.
for ((index = 1; index < ${#arguments[@]}; index++)); do
    argument="${arguments[$index]}"
    case "$argument" in
        --output-dir)
            index=$((index + 1))
            [[ $index -lt ${#arguments[@]} ]] || {
                echo "Error: --output-dir requires a value" >&2
                exit 2
            }
            output_dir="${arguments[$index]}"
            ;;
        --output-dir=*)
            output_dir="${argument#*=}"
            ;;
        --prefix)
            index=$((index + 1))
            [[ $index -lt ${#arguments[@]} ]] || {
                echo "Error: --prefix requires a value" >&2
                exit 2
            }
            output_prefix="${arguments[$index]}"
            ;;
        --prefix=*)
            output_prefix="${argument#*=}"
            ;;
        --skip-centerlines)
            skip_centerlines=true
            ;;
        --gaussian-sigma)
            index=$((index + 1))
            [[ $index -lt ${#arguments[@]} ]] || {
                echo "Error: --gaussian-sigma requires a value" >&2
                exit 2
            }
            gaussian_sigma="${arguments[$index]}"
            ;;
        --gaussian-sigma=*)
            gaussian_sigma="${argument#*=}"
            ;;
        --extrusion-percentage)
            index=$((index + 1))
            [[ $index -lt ${#arguments[@]} ]] || {
                echo "Error: --extrusion-percentage requires a value" >&2
                exit 2
            }
            extrusion_percentage="${arguments[$index]}"
            ;;
        --extrusion-percentage=*)
            extrusion_percentage="${argument#*=}"
            ;;
        --cells-per-radius)
            index=$((index + 1))
            [[ $index -lt ${#arguments[@]} ]] || {
                echo "Error: --cells-per-radius requires a value" >&2
                exit 2
            }
            cells_per_radius="${arguments[$index]}"
            ;;
        --cells-per-radius=*)
            cells_per_radius="${argument#*=}"
            ;;
        --sphere-radius-factor)
            index=$((index + 1))
            [[ $index -lt ${#arguments[@]} ]] || {
                echo "Error: --sphere-radius-factor requires a value" >&2
                exit 2
            }
            sphere_radius_factor="${arguments[$index]}"
            ;;
        --sphere-radius-factor=*)
            sphere_radius_factor="${argument#*=}"
            ;;
        --thickness-smoothing-passes)
            index=$((index + 1))
            [[ $index -lt ${#arguments[@]} ]] || {
                echo "Error: --thickness-smoothing-passes requires a value" >&2
                exit 2
            }
            thickness_smoothing_passes="${arguments[$index]}"
            ;;
        --thickness-smoothing-passes=*)
            thickness_smoothing_passes="${argument#*=}"
            ;;
        --refine-narrow-vessels)
            refine_narrow_vessels=true
            ;;
        --max-mapping-distance)
            index=$((index + 1))
            [[ $index -lt ${#arguments[@]} ]] || {
                echo "Error: --max-mapping-distance requires a value" >&2
                exit 2
            }
            max_mapping_distance="${arguments[$index]}"
            ;;
        --max-mapping-distance=*)
            max_mapping_distance="${argument#*=}"
            ;;
    esac
done

# Ask for the two wall-model parameters when running interactively and the
# corresponding options were omitted. Pressing Enter accepts the displayed
# defaults. Batch jobs have no terminal on stdin, so they use the same defaults
# without waiting; pass explicit flags in a job script for other values.
if [[ "$skip_centerlines" == false ]]; then
    if [[ -z "$gaussian_sigma" ]]; then
        if [[ -t 0 ]]; then
            read -r -p "Gaussian smoothing sigma [10.0]: " gaussian_sigma
        fi
        gaussian_sigma="${gaussian_sigma:-10.0}"
    fi

    if [[ -z "$extrusion_percentage" ]]; then
        if [[ -t 0 ]]; then
            read -r -p "Extrusion percentage [5.0]: " extrusion_percentage
        fi
        extrusion_percentage="${extrusion_percentage:-5.0}"
    fi

    echo "Gaussian smoothing sigma: $gaussian_sigma"
    echo "Extrusion percentage: $extrusion_percentage%"
fi

# Both stages need the Gaussian and extrusion options: Gauss.py turns them into
# the wall thickness, and pulmonary_centerlines.py uses the same numbers to set
# the saddle-rounding target. Strip whichever form the caller used, then append
# the resolved values once, so an interactively entered value is passed on too.
geometry_arguments=("${arguments[0]}")
for ((index = 1; index < ${#arguments[@]}; index++)); do
    argument="${arguments[$index]}"
    case "$argument" in
        --refine-narrow-vessels)
            ;;
        --gaussian-sigma|--extrusion-percentage|--cells-per-radius|--sphere-radius-factor|--thickness-smoothing-passes|--max-mapping-distance)
            index=$((index + 1))
            ;;
        --gaussian-sigma=*|--extrusion-percentage=*|--cells-per-radius=*|--sphere-radius-factor=*|--thickness-smoothing-passes=*|--max-mapping-distance=*)
            ;;
        *)
            geometry_arguments+=("$argument")
            ;;
    esac
done

if [[ "$skip_centerlines" == false ]]; then
    geometry_arguments+=(
        --gaussian-sigma "$gaussian_sigma"
        --extrusion-percentage "$extrusion_percentage"
    )
fi

# With no explicit output directory, derive the case name from the first
# argument (the input STL). For example, artery.stl becomes:
#   <fsiScript>/caseFiles/artery/
if [[ -z "$output_dir" ]]; then
    default_output_dir="$SCRIPT_DIR/caseFiles/$case_name"

    # Add the generated option to the argument array passed to Python. The
    # Python writer creates this directory, including missing parents.
    geometry_arguments+=(--output-dir "$default_output_dir")
    output_dir="$default_output_dir"
fi

# Match pathlib.Path.resolve() in the Python scripts so relative paths and '~'
# resolve consistently before filenames are constructed for the next stage.
output_dir="$($FSI_PYTHON -c \
    'from pathlib import Path; import sys; print(Path(sys.argv[1]).expanduser().resolve())' \
    "$output_dir")"
echo "Output directory: $output_dir"

# Run only this command with PYTHONPATH and LD_LIBRARY_PATH removed so OpenFOAM
# cannot inject an incompatible Python package or shared VTK library. Setting
# PYTHONNOUSERSITE also prevents packages under ~/.local from overriding the
# tested Conda packages. These changes do not alter the caller's shell.
mkdir -p "$output_dir"
geometry_log="$output_dir/log.geometry"
env -u PYTHONPATH -u LD_LIBRARY_PATH PYTHONNOUSERSITE=1 \
    "$FSI_PYTHON" "$CENTERLINE_SCRIPT" "${geometry_arguments[@]}" 2>&1 \
    | tee "$geometry_log"

# The patch check below compares what autoPatch finds against the number of
# open profiles this stage reported.
profile_count="$(sed -n 's/^Detected \([0-9][0-9]*\) open profiles$/\1/p' \
    "$geometry_log" | head -1)"
profile_count="${profile_count:-0}"

# Populate the generated case with the reusable OpenFOAM/cfMesh template. The
# trailing '/.' copies the contents, producing fluidMeshing and varExtrudeFunc
# directly below the case directory while retaining the generated geometry.
cp -a "$TEMPLATE_MESH_DIR/." "$output_dir/"

# Convert the newly capped, watertight STL to cfMesh's FMS format. Keep the FMS
# in the fluidMeshing case root and make meshDict refer to this case-specific
# surface filename.
capped_stl="$output_dir/${output_prefix}_capped.stl"
fms_name="$(basename -- "${output_prefix}_capped.fms")"
surface_dir="$output_dir/fluidMeshing"
fms_path="$surface_dir/$fms_name"
mesh_dict="$output_dir/fluidMeshing/system/meshDict"

if [[ ! -f "$capped_stl" ]]; then
    echo "Error: capped STL was not generated: $capped_stl" >&2
    exit 1
fi
if [[ ! -f "$mesh_dict" ]]; then
    echo "Error: copied meshDict not found: $mesh_dict" >&2
    exit 1
fi

mkdir -p "$surface_dir"
run_step "Extracting surface feature edges..." "$surface_dir" \
    log.surfaceFeatureEdges "$SURFACE_FEATURE_EDGES" "$capped_stl" "$fms_path"
if [[ ! -s "$fms_path" ]]; then
    echo "Error: surfaceFeatureEdges did not create a non-empty FMS file: $fms_path" >&2
    exit 1
fi

# Replace exactly the active surfaceFile entry without changing the source
# template. cfMesh resolves the filename from the case root.
escaped_fms_name="${fms_name//\\/\\\\}"
escaped_fms_name="${escaped_fms_name//&/\\&}"
escaped_fms_name="${escaped_fms_name//|/\\|}"
sed -i -E \
    "s|^[[:space:]]*surfaceFile[[:space:]]+\"[^\"]*\"[[:space:]]*;|surfaceFile \"$escaped_fms_name\";|" \
    "$mesh_dict"
if ! grep -Fqx "surfaceFile \"$fms_name\";" "$mesh_dict"; then
    echo "Error: failed to update surfaceFile in $mesh_dict" >&2
    exit 1
fi

echo "Copied mesh template to: $output_dir"
echo "Wrote cfMesh surface: $fms_path"
echo "Updated mesh dictionary: $mesh_dict"

# Size a refinement sphere for every outlet that is only a few cells across.
# Without this an outlet cap merges into the vessel wall during autoPatch.
profiles_csv="$output_dir/${output_prefix}_profiles.csv"
centerlines_vtp="$output_dir/${output_prefix}_centerlines.vtp"
refinement_options=(--cells-per-radius "$cells_per_radius"
                    --sphere-radius-factor "$sphere_radius_factor")

# Narrow-vessel cone refinement is off unless asked for: the refinement-level
# transitions it puts on the wall patch damage the extruded solid more than the
# faceting it removes.
if [[ "$refine_narrow_vessels" == true && -f "$centerlines_vtp" ]]; then
    refinement_options+=(--centerlines "$centerlines_vtp")
fi
if [[ -f "$profiles_csv" ]]; then
    "$FSI_PYTHON" "$REFINEMENT_SCRIPT" "$mesh_dict" "$profiles_csv" \
        "${refinement_options[@]}"
else
    echo "Warning: no profile table at $profiles_csv; meshDict refinements unchanged" >&2
fi

# Generate and validate the fluid volume mesh from within its OpenFOAM case.
# Each utility's full output goes to its own log in the case directory; only a
# one-line description of the step is printed.
fluid_case="$output_dir/fluidMeshing"
run_step "Meshing the fluid..." "$fluid_case" log.cartesianMesh "$CARTESIAN_MESH"
run_step "Checking the fluid mesh..." "$fluid_case" log.checkMesh \
    "$CHECK_MESH" -allTopology -allGeometry
echo "  checkMesh report: $fluid_case/log.checkMesh"

# Preview automatic surface segmentation at a 50-degree feature angle. Without
# -overwrite, autoPatch writes a new time so the original mesh remains intact
# while the user reviews the detected patch count and sizes.
run_step "Detecting boundary patches..." "$fluid_case" log.autoPatch.preview \
    "$AUTO_PATCH" 50
preview_time="$(cd "$fluid_case" && "$FOAM_LIST_TIMES" -latestTime -noZero)"
preview_boundary="$fluid_case/$preview_time/polyMesh/boundary"
if [[ -z "$preview_time" || ! -f "$preview_boundary" ]]; then
    echo "Error: could not locate the preview mesh written by autoPatch" >&2
    exit 1
fi

# Extract '<patch-name> <nFaces>' pairs from an OpenFOAM boundary file.
patch_sizes() {
    awk '
        /^[[:space:]]*[A-Za-z_][A-Za-z0-9_]*[[:space:]]*$/ {
            candidate = $1
        }
        $1 == "nFaces" {
            count = $2
            sub(/;.*/, "", count)
            print candidate, count
        }
    ' "$1"
}

mapfile -t preview_patches < <(patch_sizes "$preview_boundary")
if (( ${#preview_patches[@]} < 2 )); then
    echo "Error: autoPatch detected fewer than two patches" >&2
    exit 1
fi

# Write the full patch table to a file and report only the counts. One patch
# is expected per open profile, plus the vessel wall itself.
patch_table="$fluid_case/log.patches"
{
    printf '%-32s %s\n' "Patch" "Faces"
    for patch_entry in "${preview_patches[@]}"; do
        read -r patch_name patch_faces <<< "$patch_entry"
        printf '%-32s %s\n' "$patch_name" "$patch_faces"
    done
} > "$patch_table"

nonzero_patches=0
for patch_entry in "${preview_patches[@]}"; do
    read -r patch_name patch_faces <<< "$patch_entry"
    if (( patch_faces > 0 )); then
        nonzero_patches=$((nonzero_patches + 1))
    fi
done

if (( profile_count > 0 )); then
    expected_patches=$((profile_count + 1))
    echo "Found $nonzero_patches patches with faces; expected $expected_patches ($profile_count open profiles + 1 wall)."
else
    echo "Found $nonzero_patches patches with faces."
fi
echo "  Patch sizes: $patch_table"

if [[ ! -t 0 ]]; then
    echo "Error: patch confirmation requires an interactive terminal." >&2
    echo "Inspect $preview_boundary and rerun meshing.sh interactively." >&2
    exit 1
fi
read -r -p "Are these detected patches correct? [y/N]: " patch_confirmation
case "$patch_confirmation" in
    y|Y|yes|YES|Yes)
        ;;
    *)
        echo "Patch assignment was not accepted; stopping before modifying the mesh."
        exit 1
        ;;
esac

# Remove the preview time and apply the accepted segmentation to the constant
# mesh. This deliberately follows the reviewed preview with the same angle.
( cd "$fluid_case" && "$FOAM_LIST_TIMES" -rm > log.foamListTimes 2>&1 )
run_step "Applying patch segmentation..." "$fluid_case" log.autoPatch \
    "$AUTO_PATCH" 50 -overwrite

boundary_file="$fluid_case/constant/polyMesh/boundary"
mapfile -t ranked_patches < <(patch_sizes "$boundary_file" | sort -k2,2nr)
if (( ${#ranked_patches[@]} < 2 )); then
    echo "Error: the overwritten mesh contains fewer than two patches" >&2
    exit 1
fi
read -r largest_patch largest_faces <<< "${ranked_patches[0]}"
read -r second_patch second_faces <<< "${ranked_patches[1]}"

# Rename the two largest patches. The required zero-face outerWall patch is
# inserted directly into polyMesh/boundary after createPatch finishes, since
# createPatch deliberately removes all empty patches.
generated_patch_dict="$fluid_case/system/autoPatchCreatePatchDict"
{
    cat <<EOF
FoamFile
{
    format      ascii;
    class       dictionary;
    object      createPatchDict;
}

pointSync false;

patches
(
    {
        name wall;
        patchInfo { type wall; }
        constructFrom patches;
        patches ($largest_patch);
    }
    {
        name inlet;
        patchInfo { type patch; }
        constructFrom patches;
        patches ($second_patch);
    }
);
EOF
} > "$generated_patch_dict"
run_step "Naming the fluid patches..." "$fluid_case" log.createPatch \
    "$CREATE_PATCH" -overwrite -dict system/autoPatchCreatePatchDict
"$FSI_PYTHON" "$EMPTY_PATCH_SCRIPT" "$boundary_file" outerWall wall

# Confirm both the declared patch count and the exact zero-face entry were
# written before allowing thickness mapping and solid extrusion to continue.
if ! awk '
    $1 == "outerWall" { inPatch = 1; next }
    inPatch && $1 == "type" && $2 == "wall;" { hasType = 1 }
    inPatch && $1 == "nFaces" && $2 == "0;" { hasFaces = 1 }
    inPatch && $1 == "startFace" { hasStart = 1 }
    inPatch && $1 == "}" { exit !(hasType && hasFaces && hasStart) }
    END { if (!inPatch) exit 1 }
' "$boundary_file"; then
    echo "Error: outerWall was not written correctly to $boundary_file" >&2
    exit 1
fi
echo "Renamed largest patch '$largest_patch' ($largest_faces faces) to 'wall'."
echo "Renamed second-largest patch '$second_patch' ($second_faces faces) to 'inlet'."
echo "Created empty solid-extrusion back patch 'outerWall'."

# Centerline output is intentionally absent when --skip-centerlines is used.
# Otherwise, export the file just generated above to a CSV with the same prefix.
if [[ "$skip_centerlines" == false ]]; then
    centerline_vtp="$output_dir/${output_prefix}_centerlines.vtp"
    centerline_csv="$output_dir/${output_prefix}_centerlines.csv"

    env -u PYTHONPATH -u LD_LIBRARY_PATH PYTHONNOUSERSITE=1 \
        "$FSI_PYTHON" "$CSV_SCRIPT" "$centerline_vtp" "$centerline_csv"

    # Map the smoothed local diameter and percentage-based wall thickness to
    # the uncapped inner surface for subsequent extrusion or solid-wall steps.
    uncapped_vtp="$output_dir/${output_prefix}_uncapped.vtp"
    thickness_vtk="$output_dir/${output_prefix}_wall_thickness.vtk"
    env -u PYTHONPATH -u LD_LIBRARY_PATH PYTHONNOUSERSITE=1 \
        "$FSI_PYTHON" "$GAUSS_SCRIPT" \
        "$uncapped_vtp" "$centerline_csv" "$thickness_vtk" \
        --gaussian-sigma "$gaussian_sigma" \
        --extrusion-percentage "$extrusion_percentage" \
        --thickness-smoothing-passes "$thickness_smoothing_passes"

    # mapExtrudeDistance reads thickMap.vtk from the current OpenFOAM case by
    # default and writes the pointScalarField 0/WallThickness for the wall
    # extrusion stage.
    thick_map="$fluid_case/thickMap.vtk"
    mv -f "$thickness_vtk" "$thick_map"
    run_step "Mapping wall thickness onto the fluid wall..." "$fluid_case" \
        log.mapExtrudeDistance "$MAP_EXTRUDE_DISTANCE" \
        -maxDistance "$max_mapping_distance"
    echo "  Mapped from: $thick_map"
    echo "  mapExtrudeDistance log: $fluid_case/log.mapExtrudeDistance"

    # Extrude the mapped fluid wall into a separate conformal solid mesh. The
    # varExtrudeFunc dictionary reads ../fluidMeshing/0/WallThickness and uses
    # the temporary zero-face outerWall patch for the exposed-patch metadata.
    solid_case="$output_dir/varExtrudeFunc"
    run_step "Extruding the solid wall..." "$solid_case" log.varExtrudeMesh \
        "$VAR_EXTRUDE_MESH"
    echo "  varExtrudeMesh log: $solid_case/log.varExtrudeMesh"

    # varExtrudeMesh no longer needs the temporary zero-face patch. Running
    # createPatch with an empty operation list removes empty patches while
    # leaving all non-empty fluid patches unchanged.
    fluid_cleanup_dict="$fluid_case/system/removeEmptyPatchesDict"
    {
        cat <<'EOF'
FoamFile
{
    format      ascii;
    class       dictionary;
    object      createPatchDict;
}

pointSync false;
patches ();
EOF
    } > "$fluid_cleanup_dict"
    run_step "Removing the temporary fluid patch..." "$fluid_case" \
        log.removeEmptyPatches "$CREATE_PATCH" -overwrite \
        -dict system/removeEmptyPatchesDict

    # On the extruded solid, the old outerWall is the conformal fluid-facing
    # surface and the old wall is the exterior surface. Rename both. The inlet
    # and auto-named outlets first receive temporary names: createPatch retains
    # the old type when source and destination names are identical, whereas a
    # new temporary patch reliably receives the requested symmetry type.
    solid_patch_dict="$solid_case/system/solidCreatePatchDict"
    solid_symmetry_dict="$solid_case/system/solidSymmetryPatchDict"
    mapfile -t solid_auto_patch_names < <(
        patch_sizes "$solid_case/constant/polyMesh/boundary" |
            awk '$1 ~ /^auto/ { print $1 }'
    )
    {
        cat <<'EOF'
FoamFile
{
    format      ascii;
    class       dictionary;
    object      createPatchDict;
}

pointSync false;

patches
(
    {
        name innerWall;
        patchInfo { type wall; }
        constructFrom patches;
        patches (outerWall);
    }
    {
        name outerWall;
        patchInfo { type wall; }
        constructFrom patches;
        patches (wall);
    }
    {
        name symmetry_inlet_tmp;
        patchInfo { type symmetry; }
        constructFrom patches;
        patches (inlet);
    }
EOF
        for solid_patch_name in "${solid_auto_patch_names[@]}"; do
            cat <<EOF
    {
        name symmetry_${solid_patch_name}_tmp;
        patchInfo { type symmetry; }
        constructFrom patches;
        patches ($solid_patch_name);
    }
EOF
        done
        cat <<'EOF'
);
EOF
    } > "$solid_patch_dict"
    run_step "Naming the solid patches..." "$solid_case" log.createPatch \
        "$CREATE_PATCH" -overwrite -dict system/solidCreatePatchDict

    # Restore the public inlet and auto patch names in a second pass. Their
    # source patches are already symmetry patches, and explicitly repeating the
    # type also makes the intended final boundary definition unambiguous.
    {
        cat <<'EOF'
FoamFile
{
    format      ascii;
    class       dictionary;
    object      createPatchDict;
}

pointSync false;

patches
(
    {
        name inlet;
        patchInfo { type symmetry; }
        constructFrom patches;
        patches (symmetry_inlet_tmp);
    }
EOF
        for solid_patch_name in "${solid_auto_patch_names[@]}"; do
            cat <<EOF
    {
        name $solid_patch_name;
        patchInfo { type symmetry; }
        constructFrom patches;
        patches (symmetry_${solid_patch_name}_tmp);
    }
EOF
        done
        cat <<'EOF'
);
EOF
    } > "$solid_symmetry_dict"
    run_step "Setting the solid end patches to symmetry..." "$solid_case" \
        log.createPatch.symmetry "$CREATE_PATCH" -overwrite \
        -dict system/solidSymmetryPatchDict

    expected_symmetry_count=$((1 + ${#solid_auto_patch_names[@]}))
    verified_symmetry_count="$(awk '
        /^[[:space:]]*[A-Za-z_][A-Za-z0-9_]*[[:space:]]*$/ {
            candidate = $1
        }
        $1 == "type" && (candidate == "inlet" || candidate ~ /^auto/) {
            type = $2
            sub(/;.*/, "", type)
            if (type != "symmetry") {
                printf "Error: solid patch %s has type %s, expected symmetry\n", \
                    candidate, type > "/dev/stderr"
                failed = 1
            }
            count++
        }
        END {
            if (failed) exit 1
            print count + 0
        }
    ' "$solid_case/constant/polyMesh/boundary")" || exit 1
    if (( verified_symmetry_count != expected_symmetry_count )); then
        echo "Error: expected $expected_symmetry_count solid symmetry patches, found $verified_symmetry_count" >&2
        exit 1
    fi

    echo "Generated solid wall mesh in: $solid_case"
    echo "Removed the temporary zero-face outerWall patch from the fluid mesh."
    echo "Renamed solid outerWall to innerWall and solid wall to outerWall."
    echo "Changed the solid inlet and auto-named outlet patches to symmetry."

    # Assemble the coupled FSI run case from the reusable template. The case is
    # named after the input geometry (for example, p16.stl creates run/p16).
    # Refuse to merge with an existing case because old mesh files could remain
    # and produce a run case that does not match the newly generated geometry.
    run_case="$RUN_DIR/$case_name"
    fluid_poly_mesh="$fluid_case/constant/polyMesh"
    solid_poly_mesh="$solid_case/constant/polyMesh"

    if [[ ! -d "$fluid_poly_mesh" ]]; then
        echo "Error: generated fluid polyMesh not found: $fluid_poly_mesh" >&2
        exit 1
    fi
    if [[ ! -d "$solid_poly_mesh" ]]; then
        echo "Error: generated solid polyMesh not found: $solid_poly_mesh" >&2
        exit 1
    fi
    if [[ -e "$run_case" ]]; then
        echo "Error: run case already exists: $run_case" >&2
        echo "Move or remove it before rerunning meshing.sh." >&2
        exit 1
    fi

    mkdir -p "$RUN_DIR"
    cp -a "$TEMPLATE_CASE_DIR" "$run_case"
    cp -a "$fluid_poly_mesh" "$run_case/constant/fluid/"
    cp -a "$solid_poly_mesh" "$run_case/constant/solid/"

    echo "Created coupled run case in: $run_case"
    echo "Copied fluid mesh to: $run_case/constant/fluid/polyMesh"
    echo "Copied solid mesh to: $run_case/constant/solid/polyMesh"
else
    echo "Skipping CSV and wall-thickness mapping because --skip-centerlines was supplied."
fi


# Offer to remove only the intermediate caseFiles directory created for this
# geometry. Never recursively remove a custom --output-dir, since it may also
# contain files that were not generated by this script. Batch runs retain the
# intermediate files because they cannot provide explicit confirmation.
case_files_dir="$SCRIPT_DIR/caseFiles/$case_name"
if [[ -n "$case_name" && "$case_name" != "." && "$case_name" != ".." &&
      "$output_dir" == "$case_files_dir" && -d "$case_files_dir" && -t 0 ]]; then
    read -r -p "Remove the intermediate meshing case '$case_files_dir'? [y/N]: " remove_case
    case "$remove_case" in
        y|Y|yes|YES|Yes)
            rm -rf -- "$case_files_dir"
            echo "Removed intermediate meshing case: $case_files_dir"
            ;;
        *)
            echo "Retained intermediate meshing case: $case_files_dir"
            ;;
    esac
elif [[ "$output_dir" != "$case_files_dir" ]]; then
    echo "Retained custom meshing output directory: $output_dir"
fi

echo "Note"
echo "make sure that mesh is in units of metres (or else)"
echo "First check with any issues for self-intersection of the solid mesh"
echo "Try smoothing the mesh or a lower extrusion percentage if this is the case"
