#!/usr/bin/env bash

# Stop on a failed command (-e), an unset variable (-u), or a failed command
# inside a pipeline (pipefail). This prevents the workflow continuing with
# missing or incomplete geometry.
set -euo pipefail

# Find the directory containing this script, even when meshing.sh is launched
# from another working directory. BASH_SOURCE[0] is the path to this file.
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

# Construct an absolute path to the Python geometry-processing script.
CENTERLINE_SCRIPT="$SCRIPT_DIR/pythonScripts/pulmonary_centerlines.py"
CSV_SCRIPT="$SCRIPT_DIR/pythonScripts/centerlines_to_csv.py"
GAUSS_SCRIPT="$SCRIPT_DIR/pythonScripts/Gauss.py"
EMPTY_PATCH_SCRIPT="$SCRIPT_DIR/pythonScripts/add_empty_boundary_patch.py"
REFINEMENT_SCRIPT="$SCRIPT_DIR/pythonScripts/add_refinements.py"
WINDKESSEL_SCRIPT="$SCRIPT_DIR/pythonScripts/windkessel_outlets.py"
TEMPLATE_MESH_DIR="$SCRIPT_DIR/templateMesh"
TEMPLATE_CASE_DIR="$SCRIPT_DIR/templateCase"
TEMPLATE_CASE_ROBIN_DIR="$SCRIPT_DIR/templateCaseRobin"
RUN_DIR="$SCRIPT_DIR/run"

# Allow an alternate cfMesh installation to be selected on systems where the
# utility is not on PATH.
SURFACE_FEATURE_EDGES="${SURFACE_FEATURE_EDGES:-surfaceFeatureEdges}"
CARTESIAN_MESH="${CARTESIAN_MESH:-cartesianMesh}"
CHECK_MESH="${CHECK_MESH:-checkMesh}"
MAP_EXTRUDE_DISTANCE="${MAP_EXTRUDE_DISTANCE:-mapExtrudeDistance}"
CREATE_PATCH="${CREATE_PATCH:-createPatch}"
VAR_EXTRUDE_MESH="${VAR_EXTRUDE_MESH:-varExtrudeMesh}"
TRANSFORM_POINTS="${TRANSFORM_POINTS:-transformPoints}"

# Use the repository's fsi-env Python by default. If an HPC user stores the
# environment elsewhere, an existing FSI_PYTHON environment variable overrides
# this default; for example: export FSI_PYTHON=/project/fsi-env/bin/python.
FSI_PYTHON="${FSI_PYTHON:-$SCRIPT_DIR/.env/fsi-env/bin/python}"

# Fail early with an actionable message if the selected Python is absent or is
# not executable. The -x test checks both existence and execute permission.
if [[ ! -x "$FSI_PYTHON" ]]; then
    cat >&2 <<EOF
Error: the FSI Python executable was not found:
  $FSI_PYTHON

Set FSI_PYTHON to the Python executable in an environment containing VTK and
VMTK, for example:
  export FSI_PYTHON=/path/to/fsi-env/bin/python
EOF
    exit 1
fi

# Fail before processing if the repository's Python script is missing.
if [[ ! -f "$CENTERLINE_SCRIPT" ]]; then
    echo "Error: centerline script not found: $CENTERLINE_SCRIPT" >&2
    exit 1
fi

# The CSV exporter runs immediately after successful centerline extraction.
if [[ ! -f "$CSV_SCRIPT" ]]; then
    echo "Error: CSV export script not found: $CSV_SCRIPT" >&2
    exit 1
fi

# Gauss.py maps smoothed centerline diameters and the requested wall thickness
# onto the uncapped surface generated by the first stage.
if [[ ! -f "$GAUSS_SCRIPT" ]]; then
    echo "Error: Gaussian thickness script not found: $GAUSS_SCRIPT" >&2
    exit 1
fi

if [[ ! -f "$EMPTY_PATCH_SCRIPT" ]]; then
    echo "Error: empty boundary patch script not found: $EMPTY_PATCH_SCRIPT" >&2
    exit 1
fi

if [[ ! -f "$REFINEMENT_SCRIPT" ]]; then
    echo "Error: refinement script not found: $REFINEMENT_SCRIPT" >&2
    exit 1
fi

if [[ ! -f "$WINDKESSEL_SCRIPT" ]]; then
    echo "Error: Windkessel split script not found: $WINDKESSEL_SCRIPT" >&2
    exit 1
fi

if [[ ! -d "$TEMPLATE_MESH_DIR" ]]; then
    echo "Error: mesh template directory not found: $TEMPLATE_MESH_DIR" >&2
    exit 1
fi

if [[ ! -d "$TEMPLATE_CASE_DIR" ]]; then
    echo "Error: case template directory not found: $TEMPLATE_CASE_DIR" >&2
    exit 1
fi

if ! command -v "$SURFACE_FEATURE_EDGES" >/dev/null 2>&1; then
    echo "Error: surfaceFeatureEdges executable not found: $SURFACE_FEATURE_EDGES" >&2
    exit 1
fi

for required_utility in \
    "$CARTESIAN_MESH" "$CHECK_MESH" "$MAP_EXTRUDE_DISTANCE" \
    "$CREATE_PATCH" \
    "$VAR_EXTRUDE_MESH" "$TRANSFORM_POINTS"; do
    if ! command -v "$required_utility" >/dev/null 2>&1; then
        echo "Error: required meshing utility not found: $required_utility" >&2
        exit 1
    fi
done

# Run one meshing utility inside its case directory with all of its output
# captured in a log file, printing only a short description of the step. The
# log is named in the error message so a failure can still be diagnosed.
run_step() {
    local description="$1" work_dir="$2" log_name="$3"
    shift 3
    echo "$description"
    if ! ( cd "$work_dir" && "$@" > "$log_name" 2>&1 ); then
        echo "Error: step failed: $description" >&2
        echo "See $work_dir/$log_name" >&2
        exit 1
    fi
}

# Exit with a usage error unless the value is a plain positive number.
require_positive_number() {
    local value="$1" option="$2"
    if ! awk -v value="$value" 'BEGIN {
            exit !(value ~ /^[+]?([0-9]+[.]?[0-9]*|[.][0-9]+)([eE][-+]?[0-9]+)?$/ && value + 0 > 0)
        }'; then
        echo "Error: $option must be a positive number, not '$value'" >&2
        exit 2
    fi
}

# At least the input STL positional argument is required. Exit status 2 denotes
# invalid command-line usage.
if [[ $# -eq 0 ]]; then
    echo "Usage: $0 INPUT.stl [--gaussian-sigma VALUE] [--extrusion-percentage VALUE]" >&2
    echo "       [--output-dir DIR] [--prefix NAME]" >&2
    echo "       [--smoothing-iterations N] [--smoothing-passband VALUE]" >&2
    echo "       [--extension-diameters VALUE] [--no-saddle-smoothing]" >&2
    echo "       [--saddle-safety-factor VALUE]" >&2
    echo "       [--saddle-dilation N] [--cells-per-radius VALUE]" >&2
    echo "       [--sphere-radius-factor VALUE]" >&2
    echo "       [--thickness-smoothing-passes N]" >&2
    echo "       [--max-mapping-distance VALUE] [--maximum-refinement-levels N]" >&2
    echo "       [--coupling robin|dirichlet] [--scale-factor VALUE]" >&2
    echo "       [--wk-proximal-resistance VALUE] [--wk-distal-resistance VALUE]" >&2
    echo "       [--wk-compliance VALUE] [--flow-split-exponent VALUE]" >&2
    echo "       [--species human|porcine] [--heartbeats N] [--cores N]" >&2
    exit 2
fi

# Copy every command-line argument into an array. Using an array preserves
# spaces and special characters in paths when the arguments are forwarded.
arguments=("$@")

# Derive the default output prefix from the STL filename. These values are also
# used below to identify the exact centerline VTP produced by the Python step.
input_name="$(basename -- "$1")"
case_name="${input_name%.*}"
output_prefix="$case_name"
output_dir=""
gaussian_sigma=""
extrusion_percentage=""
coupling=""
scale_factor=""
wk_proximal_resistance=""
wk_distal_resistance=""
wk_compliance=""
flow_split_exponent="2"
species=""
heartbeats=""
cores=""
cells_per_radius="3.0"
sphere_radius_factor="4.0"
maximum_refinement_levels="1"
thickness_smoothing_passes="10"
# mapExtrudeDistance aborts if any wall point is further than this from the
# thickness-map surface. Its own default of 0.2 is far tighter than a 1 mm mesh
# warrants: cfMesh snapping leaves a handful of rim points a few tenths of a
# millimetre out, which is harmless because the thickness field is smooth there.
# This stays small enough to still catch a units or geometry mismatch.
max_mapping_distance="1.0"

# Read the output-related options without removing them from the array that is
# passed to pulmonary_centerlines.py. Both --option value and --option=value
# forms are supported.
for ((index = 1; index < ${#arguments[@]}; index++)); do
    argument="${arguments[$index]}"
    case "$argument" in
        --output-dir)
            index=$((index + 1))
            [[ $index -lt ${#arguments[@]} ]] || {
                echo "Error: --output-dir requires a value" >&2
                exit 2
            }
            output_dir="${arguments[$index]}"
            ;;
        --output-dir=*)
            output_dir="${argument#*=}"
            ;;
        --prefix)
            index=$((index + 1))
            [[ $index -lt ${#arguments[@]} ]] || {
                echo "Error: --prefix requires a value" >&2
                exit 2
            }
            output_prefix="${arguments[$index]}"
            ;;
        --prefix=*)
            output_prefix="${argument#*=}"
            ;;
        --skip-centerlines)
            echo "Error: --skip-centerlines was removed; the run case needs the centerlines" >&2
            exit 2
            ;;
        --gaussian-sigma)
            index=$((index + 1))
            [[ $index -lt ${#arguments[@]} ]] || {
                echo "Error: --gaussian-sigma requires a value" >&2
                exit 2
            }
            gaussian_sigma="${arguments[$index]}"
            ;;
        --gaussian-sigma=*)
            gaussian_sigma="${argument#*=}"
            ;;
        --extrusion-percentage)
            index=$((index + 1))
            [[ $index -lt ${#arguments[@]} ]] || {
                echo "Error: --extrusion-percentage requires a value" >&2
                exit 2
            }
            extrusion_percentage="${arguments[$index]}"
            ;;
        --extrusion-percentage=*)
            extrusion_percentage="${argument#*=}"
            ;;
        --coupling)
            index=$((index + 1))
            [[ $index -lt ${#arguments[@]} ]] || {
                echo "Error: --coupling requires a value" >&2
                exit 2
            }
            coupling="${arguments[$index]}"
            ;;
        --coupling=*)
            coupling="${argument#*=}"
            ;;
        --scale-factor)
            index=$((index + 1))
            [[ $index -lt ${#arguments[@]} ]] || {
                echo "Error: --scale-factor requires a value" >&2
                exit 2
            }
            scale_factor="${arguments[$index]}"
            ;;
        --scale-factor=*)
            scale_factor="${argument#*=}"
            ;;
        --wk-proximal-resistance)
            index=$((index + 1))
            [[ $index -lt ${#arguments[@]} ]] || {
                echo "Error: --wk-proximal-resistance requires a value" >&2
                exit 2
            }
            wk_proximal_resistance="${arguments[$index]}"
            ;;
        --wk-proximal-resistance=*)
            wk_proximal_resistance="${argument#*=}"
            ;;
        --wk-distal-resistance)
            index=$((index + 1))
            [[ $index -lt ${#arguments[@]} ]] || {
                echo "Error: --wk-distal-resistance requires a value" >&2
                exit 2
            }
            wk_distal_resistance="${arguments[$index]}"
            ;;
        --wk-distal-resistance=*)
            wk_distal_resistance="${argument#*=}"
            ;;
        --wk-compliance)
            index=$((index + 1))
            [[ $index -lt ${#arguments[@]} ]] || {
                echo "Error: --wk-compliance requires a value" >&2
                exit 2
            }
            wk_compliance="${arguments[$index]}"
            ;;
        --wk-compliance=*)
            wk_compliance="${argument#*=}"
            ;;
        --flow-split-exponent)
            index=$((index + 1))
            [[ $index -lt ${#arguments[@]} ]] || {
                echo "Error: --flow-split-exponent requires a value" >&2
                exit 2
            }
            flow_split_exponent="${arguments[$index]}"
            ;;
        --flow-split-exponent=*)
            flow_split_exponent="${argument#*=}"
            ;;
        --species)
            index=$((index + 1))
            [[ $index -lt ${#arguments[@]} ]] || {
                echo "Error: --species requires a value" >&2
                exit 2
            }
            species="${arguments[$index]}"
            ;;
        --species=*)
            species="${argument#*=}"
            ;;
        --heartbeats)
            index=$((index + 1))
            [[ $index -lt ${#arguments[@]} ]] || {
                echo "Error: --heartbeats requires a value" >&2
                exit 2
            }
            heartbeats="${arguments[$index]}"
            ;;
        --heartbeats=*)
            heartbeats="${argument#*=}"
            ;;
        --cores)
            index=$((index + 1))
            [[ $index -lt ${#arguments[@]} ]] || {
                echo "Error: --cores requires a value" >&2
                exit 2
            }
            cores="${arguments[$index]}"
            ;;
        --cores=*)
            cores="${argument#*=}"
            ;;
        --cells-per-radius)
            index=$((index + 1))
            [[ $index -lt ${#arguments[@]} ]] || {
                echo "Error: --cells-per-radius requires a value" >&2
                exit 2
            }
            cells_per_radius="${arguments[$index]}"
            ;;
        --cells-per-radius=*)
            cells_per_radius="${argument#*=}"
            ;;
        --sphere-radius-factor)
            index=$((index + 1))
            [[ $index -lt ${#arguments[@]} ]] || {
                echo "Error: --sphere-radius-factor requires a value" >&2
                exit 2
            }
            sphere_radius_factor="${arguments[$index]}"
            ;;
        --sphere-radius-factor=*)
            sphere_radius_factor="${argument#*=}"
            ;;
        --maximum-refinement-levels)
            index=$((index + 1))
            [[ $index -lt ${#arguments[@]} ]] || {
                echo "Error: --maximum-refinement-levels requires a value" >&2
                exit 2
            }
            maximum_refinement_levels="${arguments[$index]}"
            ;;
        --maximum-refinement-levels=*)
            maximum_refinement_levels="${argument#*=}"
            ;;
        --thickness-smoothing-passes)
            index=$((index + 1))
            [[ $index -lt ${#arguments[@]} ]] || {
                echo "Error: --thickness-smoothing-passes requires a value" >&2
                exit 2
            }
            thickness_smoothing_passes="${arguments[$index]}"
            ;;
        --thickness-smoothing-passes=*)
            thickness_smoothing_passes="${argument#*=}"
            ;;
        --max-mapping-distance)
            index=$((index + 1))
            [[ $index -lt ${#arguments[@]} ]] || {
                echo "Error: --max-mapping-distance requires a value" >&2
                exit 2
            }
            max_mapping_distance="${arguments[$index]}"
            ;;
        --max-mapping-distance=*)
            max_mapping_distance="${argument#*=}"
            ;;
    esac
done

# Ask for the two wall-model parameters when running interactively and the
# corresponding options were omitted. Pressing Enter accepts the displayed
# defaults. Batch jobs have no terminal on stdin, so they use the same defaults
# without waiting; pass explicit flags in a job script for other values.
if [[ -z "$gaussian_sigma" ]]; then
    if [[ -t 0 ]]; then
        read -r -p "Gaussian smoothing sigma [10.0]: " gaussian_sigma
    fi
    gaussian_sigma="${gaussian_sigma:-10.0}"
fi

if [[ -z "$extrusion_percentage" ]]; then
    if [[ -t 0 ]]; then
        read -r -p "Extrusion percentage [5.0]: " extrusion_percentage
    fi
    extrusion_percentage="${extrusion_percentage:-5.0}"
fi

echo "Gaussian smoothing sigma: $gaussian_sigma"
echo "Extrusion percentage: $extrusion_percentage%"

# The two formulations need different interface conditions, so each has its own
# case template. Robin cases are named with a Robin suffix so both can be
# generated from one geometry without colliding.
if [[ -z "$coupling" ]]; then
    if [[ -t 0 ]]; then
        read -r -p "FSI coupling, robin or dirichlet [robin]: " coupling
    fi
    coupling="${coupling:-robin}"
fi

case "${coupling,,}" in
    dirichlet)
        coupling="dirichlet"
        case_template="$TEMPLATE_CASE_DIR"
        case_suffix=""
        ;;
    robin)
        coupling="robin"
        case_template="$TEMPLATE_CASE_ROBIN_DIR"
        case_suffix="Robin"
        ;;
    *)
        echo "Error: --coupling must be 'dirichlet' or 'robin', not '$coupling'" >&2
        exit 2
        ;;
esac

if [[ ! -d "$case_template" ]]; then
    echo "Error: case template for $coupling coupling not found: $case_template" >&2
    exit 1
fi
echo "FSI coupling: $coupling (template: $(basename -- "$case_template"))"

# The run case is named after the input geometry (for example, p16.stl creates
# run/p16Robin). Refuse to merge with an existing case, because old mesh files
# could remain and produce a case that does not match the new geometry. This is
# checked now, before any meshing, so a clash does not waste a full run.
run_case="$RUN_DIR/${case_name}${case_suffix}"
if [[ -e "$run_case" ]]; then
    echo "Error: run case already exists: $run_case" >&2
    echo "Move or remove it before rerunning meshing.sh." >&2
    exit 1
fi

# The geometry is meshed in its native STL units (millimetres for the supplied
# scans), and solids4foam expects metres. The finished run-case meshes are
# scaled by this factor with transformPoints; 1 leaves them unscaled. It is
# asked for here rather than at the end so an interactive run does not stall.
if [[ -z "$scale_factor" ]]; then
    if [[ -t 0 ]]; then
        read -r -p "Mesh scale factor applied to the run case [0.001]: " scale_factor
    fi
    scale_factor="${scale_factor:-0.001}"
fi
require_positive_number "$scale_factor" --scale-factor
echo "Mesh scale factor: $scale_factor"

# The inlet flow-rate waveform differs between species. Each template carries
# one cycle of both in constant/fluid/inletFlow, and the inlet in 0/fluid/U is
# pointed at the matching file once the run case exists.
if [[ -z "$species" ]]; then
    if [[ -t 0 ]]; then
        read -r -p "Species, human or porcine [human]: " species
    fi
    species="${species:-human}"
fi
case "${species,,}" in
    h|human)
        species="human"
        inlet_flow_file="humanFlow"
        ;;
    p|pig|porcine)
        species="porcine"
        inlet_flow_file="pigFlow"
        ;;
    *)
        echo "Error: --species must be 'human' or 'porcine', not '$species'" >&2
        exit 2
        ;;
esac
if [[ ! -f "$case_template/constant/fluid/inletFlow/$inlet_flow_file" ]]; then
    echo "Error: inlet flow file not found: $case_template/constant/fluid/inletFlow/$inlet_flow_file" >&2
    exit 1
fi
echo "Species: $species (inlet flow: $inlet_flow_file)"

# Run a whole number of cardiac cycles. The cycle length is the last time in
# the waveform file, so a replaced waveform needs no change here.
if [[ -z "$heartbeats" ]]; then
    if [[ -t 0 ]]; then
        read -r -p "Number of heartbeats to run [3]: " heartbeats
    fi
    heartbeats="${heartbeats:-3}"
fi
require_positive_number "$heartbeats" --heartbeats
cycle_period="$(awk '
    $1 == "(" && $2 ~ /^[0-9.eE+-]+$/ { last = $2 }
    END { print last }
' "$case_template/constant/fluid/inletFlow/$inlet_flow_file")"
require_positive_number "$cycle_period" "the cycle length in $inlet_flow_file"
end_time="$(awk -v n="$heartbeats" -v t="$cycle_period" 'BEGIN { printf "%.10g", n * t }')"
echo "Heartbeats: $heartbeats x ${cycle_period} s, endTime $end_time"

# Both regions are decomposed into the same number of subdomains, and the
# Slurm job asks for one task per subdomain.
if [[ -z "$cores" ]]; then
    if [[ -t 0 ]]; then
        read -r -p "Number of cores [16]: " cores
    fi
    cores="${cores:-16}"
fi
if [[ ! "$cores" =~ ^[1-9][0-9]*$ ]]; then
    echo "Error: --cores must be a positive whole number, not '$cores'" >&2
    exit 2
fi
echo "Cores: $cores"

# Three-element Windkessel totals for the whole distal bed, in SI units. They
# are split across the outlets by area once the run case exists; see
# pythonScripts/windkessel_outlets.py. Pressing Enter accepts the defaults.
if [[ -z "$wk_proximal_resistance" ]]; then
    if [[ -t 0 ]]; then
        read -r -p "Total proximal resistance Rp, Pa s/m^3 [3.3e6]: " wk_proximal_resistance
    fi
    wk_proximal_resistance="${wk_proximal_resistance:-3.3e6}"
fi
if [[ -z "$wk_distal_resistance" ]]; then
    if [[ -t 0 ]]; then
        read -r -p "Total distal resistance Rd, Pa s/m^3 [2e7]: " wk_distal_resistance
    fi
    wk_distal_resistance="${wk_distal_resistance:-2e7}"
fi
if [[ -z "$wk_compliance" ]]; then
    if [[ -t 0 ]]; then
        read -r -p "Total compliance C, m^3/Pa [3.5e-8]: " wk_compliance
    fi
    wk_compliance="${wk_compliance:-3.5e-8}"
fi
require_positive_number "$wk_proximal_resistance" --wk-proximal-resistance
require_positive_number "$wk_distal_resistance" --wk-distal-resistance
require_positive_number "$wk_compliance" --wk-compliance
require_positive_number "$flow_split_exponent" --flow-split-exponent
echo "Windkessel totals: Rp $wk_proximal_resistance, Rd $wk_distal_resistance, C $wk_compliance"
echo "Outlet flow split: Q ~ r^$flow_split_exponent"

# Both stages need the Gaussian and extrusion options: Gauss.py turns them into
# the wall thickness, and pulmonary_centerlines.py uses the same numbers to set
# the saddle-rounding target. Strip whichever form the caller used, then append
# the resolved values once, so an interactively entered value is passed on too.
geometry_arguments=("${arguments[0]}")
passthrough_arguments=()
for ((index = 1; index < ${#arguments[@]}; index++)); do
    argument="${arguments[$index]}"
    case "$argument" in
        --coupling|--scale-factor|--wk-proximal-resistance|--wk-distal-resistance|--wk-compliance|--flow-split-exponent|--species|--heartbeats|--cores|--gaussian-sigma|--extrusion-percentage|--cells-per-radius|--sphere-radius-factor|--thickness-smoothing-passes|--max-mapping-distance|--maximum-refinement-levels)
            index=$((index + 1))
            ;;
        --coupling=*|--scale-factor=*|--wk-proximal-resistance=*|--wk-distal-resistance=*|--wk-compliance=*|--flow-split-exponent=*|--species=*|--heartbeats=*|--cores=*|--gaussian-sigma=*|--extrusion-percentage=*|--cells-per-radius=*|--sphere-radius-factor=*|--thickness-smoothing-passes=*|--max-mapping-distance=*|--maximum-refinement-levels=*)
            ;;
        # Forwarded to Python, but already shown in the settings summary.
        --output-dir|--prefix)
            geometry_arguments+=("$argument" "${arguments[$((index + 1))]}")
            index=$((index + 1))
            ;;
        --output-dir=*|--prefix=*)
            geometry_arguments+=("$argument")
            ;;
        *)
            geometry_arguments+=("$argument")
            passthrough_arguments+=("$argument")
            ;;
    esac
done

geometry_arguments+=(
    --gaussian-sigma "$gaussian_sigma"
    --extrusion-percentage "$extrusion_percentage"
)

# With no explicit output directory, derive the case name from the first
# argument (the input STL). For example, artery.stl becomes:
#   <fsiScript>/caseFiles/artery/
if [[ -z "$output_dir" ]]; then
    default_output_dir="$SCRIPT_DIR/caseFiles/$case_name"

    # Add the generated option to the argument array passed to Python. The
    # Python writer creates this directory, including missing parents.
    geometry_arguments+=(--output-dir "$default_output_dir")
    output_dir="$default_output_dir"
fi

# Match pathlib.Path.resolve() in the Python scripts so relative paths and '~'
# resolve consistently before filenames are constructed for the next stage.
output_dir="$($FSI_PYTHON -c \
    'from pathlib import Path; import sys; print(Path(sys.argv[1]).expanduser().resolve())' \
    "$output_dir")"
echo "Output directory: $output_dir"

# Every resolved setting, one "name: value" per line. Shown before the long
# meshing run and recorded in the run case as meshing.params.
print_settings() {
    printf '%-28s %s\n' \
        "Input geometry:" "${arguments[0]}" \
        "Run case:" "$run_case" \
        "Meshing directory:" "$output_dir" \
        "FSI coupling:" "$coupling" \
        "Gaussian sigma:" "$gaussian_sigma" \
        "Extrusion percentage:" "$extrusion_percentage" \
        "Thickness smoothing passes:" "$thickness_smoothing_passes" \
        "Cells per radius:" "$cells_per_radius" \
        "Sphere radius factor:" "$sphere_radius_factor" \
        "Max refinement levels:" "$maximum_refinement_levels" \
        "Max mapping distance:" "$max_mapping_distance" \
        "Mesh scale factor:" "$scale_factor" \
        "Species:" "$species ($inlet_flow_file)" \
        "Heartbeats:" "$heartbeats x $cycle_period s (endTime $end_time)" \
        "Cores:" "$cores" \
        "Windkessel Rp [Pa s/m^3]:" "$wk_proximal_resistance" \
        "Windkessel Rd [Pa s/m^3]:" "$wk_distal_resistance" \
        "Windkessel C [m^3/Pa]:" "$wk_compliance" \
        "Flow-split exponent:" "$flow_split_exponent"
    if (( ${#passthrough_arguments[@]} > 0 )); then
        printf '%-28s %s\n' "Other geometry options:" "${passthrough_arguments[*]}"
    fi
}

echo
echo "Settings"
echo "--------"
print_settings
echo
if [[ -t 0 ]]; then
    read -r -p "Proceed with meshing? [Y/n]: " proceed
    case "${proceed,,}" in
        ""|y|yes) ;;
        *)
            echo "Stopped before meshing; nothing was written."
            exit 0
            ;;
    esac
fi

# Run only this command with PYTHONPATH and LD_LIBRARY_PATH removed so OpenFOAM
# cannot inject an incompatible Python package or shared VTK library. Setting
# PYTHONNOUSERSITE also prevents packages under ~/.local from overriding the
# tested Conda packages. These changes do not alter the caller's shell.
mkdir -p "$output_dir"
geometry_log="$output_dir/log.geometry"
env -u PYTHONPATH -u LD_LIBRARY_PATH PYTHONNOUSERSITE=1 \
    "$FSI_PYTHON" "$CENTERLINE_SCRIPT" "${geometry_arguments[@]}" 2>&1 \
    | tee "$geometry_log"

# The patch check below compares the patches cfMesh produced against the number
# of open profiles this stage reported.
profile_count="$(sed -n 's/^Detected \([0-9][0-9]*\) open profiles$/\1/p' \
    "$geometry_log" | head -1)"
profile_count="${profile_count:-0}"

# Populate the generated case with the reusable OpenFOAM/cfMesh template. The
# trailing '/.' copies the contents, producing fluidMeshing and varExtrudeFunc
# directly below the case directory while retaining the generated geometry.
cp -a "$TEMPLATE_MESH_DIR/." "$output_dir/"

# Convert the newly capped, watertight STL to cfMesh's FMS format. Keep the FMS
# in the fluidMeshing case root and make meshDict refer to this case-specific
# surface filename.
capped_stl="$output_dir/${output_prefix}_capped.stl"
fms_name="$(basename -- "${output_prefix}_capped.fms")"
surface_dir="$output_dir/fluidMeshing"
fms_path="$surface_dir/$fms_name"
mesh_dict="$output_dir/fluidMeshing/system/meshDict"

if [[ ! -f "$capped_stl" ]]; then
    echo "Error: capped STL was not generated: $capped_stl" >&2
    exit 1
fi
if [[ ! -f "$mesh_dict" ]]; then
    echo "Error: copied meshDict not found: $mesh_dict" >&2
    exit 1
fi

mkdir -p "$surface_dir"
run_step "Extracting surface feature edges..." "$surface_dir" \
    log.surfaceFeatureEdges "$SURFACE_FEATURE_EDGES" "$capped_stl" "$fms_path"
if [[ ! -s "$fms_path" ]]; then
    echo "Error: surfaceFeatureEdges did not create a non-empty FMS file: $fms_path" >&2
    exit 1
fi

# Give every patch its proper OpenFOAM type. An STL carries no type, so the FMS
# leaves every region "empty" and cfMesh then writes them all out as walls,
# which is wrong for the openings and makes the boundary file confusing to read.
# The FMS header is the only place this can be set: cfMesh copies each surface
# region's geometric type straight onto the mesh patch it creates from it. Only
# the vessel wall is a wall; every opening is a plain patch.
#
# meshDict's renameBoundary is not usable for this. It insists on a newName for
# every entry, and giving the outlets a shared name merges them into a single
# patch, which would cost the per-outlet boundary conditions.
"$FSI_PYTHON" - "$fms_path" <<'PYTHON_FMS_TYPES'
import re
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as handle:
    text = handle.read()

# The header is a count, an opening parenthesis, then one "name type" pair per
# region. Rewrite only inside it; the geometry that follows must not be touched.
header = re.match(r"\s*(\d+)\s*\(", text)
if header is None:
    sys.exit("error: FMS file does not start with a patch header")
count = int(header.group(1))
closing = text.index(")", header.end())

def retype(match):
    name = match.group("name")
    return f"{name} {'wall' if name == 'wall' else 'patch'}"

body, replaced = re.subn(
    r"(?m)^(?P<name>\w+)[ \t]+\w+[ \t]*$",
    retype,
    text[header.end():closing],
)
if replaced != count:
    sys.exit(f"error: retyped {replaced} of {count} FMS patches")

with open(path, "w", encoding="utf-8") as handle:
    handle.write(text[: header.end()] + body + text[closing:])
PYTHON_FMS_TYPES

# Replace exactly the active surfaceFile entry without changing the source
# template. cfMesh resolves the filename from the case root.
escaped_fms_name="${fms_name//\\/\\\\}"
escaped_fms_name="${escaped_fms_name//&/\\&}"
escaped_fms_name="${escaped_fms_name//|/\\|}"
sed -i -E \
    "s|^[[:space:]]*surfaceFile[[:space:]]+\"[^\"]*\"[[:space:]]*;|surfaceFile \"$escaped_fms_name\";|" \
    "$mesh_dict"
if ! grep -Fqx "surfaceFile \"$fms_name\";" "$mesh_dict"; then
    echo "Error: failed to update surfaceFile in $mesh_dict" >&2
    exit 1
fi

echo "Copied mesh template to: $output_dir"
echo "Wrote cfMesh surface: $fms_path"
echo "Updated mesh dictionary: $mesh_dict"

# Size a refinement sphere for every outlet that is only a few cells across.
# Without this an outlet cap merges into the vessel wall during autoPatch.
profiles_csv="$output_dir/${output_prefix}_profiles.csv"
refinement_options=(--cells-per-radius "$cells_per_radius"
                    --sphere-radius-factor "$sphere_radius_factor"
                    --maximum-refinement-levels "$maximum_refinement_levels")
if [[ -f "$profiles_csv" ]]; then
    "$FSI_PYTHON" "$REFINEMENT_SCRIPT" "$mesh_dict" "$profiles_csv" \
        "${refinement_options[@]}"
else
    echo "Warning: no profile table at $profiles_csv; meshDict refinements unchanged" >&2
fi

# Generate and validate the fluid volume mesh from within its OpenFOAM case.
# Each utility's full output goes to its own log in the case directory; only a
# one-line description of the step is printed.
fluid_case="$output_dir/fluidMeshing"
run_step "Meshing the fluid..." "$fluid_case" log.cartesianMesh "$CARTESIAN_MESH"
run_step "Checking the fluid mesh..." "$fluid_case" log.checkMesh \
    "$CHECK_MESH" -allTopology -allGeometry
echo "  checkMesh report: $fluid_case/log.checkMesh"

# The patches were decided when the surface was capped: every region of the
# capped STL is a named solid, and cfMesh turns each into a patch of the same
# name. Nothing here has to work out what an opening is.
boundary_file="$fluid_case/constant/polyMesh/boundary"

# Report each patch and refuse to continue if any named opening was meshed shut,
# which happens when a profile is too small for the cell size to resolve.
patch_sizes() {
    awk '
        /^[[:space:]]*[A-Za-z_][A-Za-z0-9_]*[[:space:]]*$/ {
            candidate = $1
        }
        $1 == "nFaces" {
            count = $2
            sub(/;.*/, "", count)
            print candidate, count
        }
    ' "$1"
}

patch_table="$fluid_case/log.patches"
{
    printf '%-32s %s\n' "Patch" "Faces"
    patch_sizes "$boundary_file" | while read -r patch_name patch_faces; do
        printf '%-32s %s\n' "$patch_name" "$patch_faces"
    done
} > "$patch_table"

empty_patches=""
outlet_count=0
while read -r patch_name patch_faces; do
    case "$patch_name" in
        wall|inlet|outlet*)
            if (( patch_faces == 0 )); then
                empty_patches="$empty_patches $patch_name"
            elif [[ "$patch_name" == outlet* ]]; then
                outlet_count=$((outlet_count + 1))
            fi
            ;;
    esac
done < <(patch_sizes "$boundary_file")

echo "Meshed 1 wall, 1 inlet and $outlet_count outlet(s); patch sizes: $patch_table"
if [[ -n "$empty_patches" ]]; then
    echo "Error: these named patches were meshed shut:$empty_patches" >&2
    echo "Their openings are too small for maxCellSize. Refine them with" >&2
    echo "--cells-per-radius or --maximum-refinement-levels, or lower" >&2
    echo "maxCellSize in the mesh template." >&2
    exit 1
fi

"$FSI_PYTHON" "$EMPTY_PATCH_SCRIPT" "$boundary_file" outerWall wall

# Confirm both the declared patch count and the exact zero-face entry were
# written before allowing thickness mapping and solid extrusion to continue.
if ! awk '
    $1 == "outerWall" { inPatch = 1; next }
    inPatch && $1 == "type" && $2 == "wall;" { hasType = 1 }
    inPatch && $1 == "nFaces" && $2 == "0;" { hasFaces = 1 }
    inPatch && $1 == "startFace" { hasStart = 1 }
    inPatch && $1 == "}" { exit !(hasType && hasFaces && hasStart) }
    END { if (!inPatch) exit 1 }
' "$boundary_file"; then
    echo "Error: outerWall was not written correctly to $boundary_file" >&2
    exit 1
fi
echo "Created empty solid-extrusion back patch 'outerWall'."

# Export the centerlines just generated above to a CSV with the same prefix.
centerline_vtp="$output_dir/${output_prefix}_centerlines.vtp"
centerline_csv="$output_dir/${output_prefix}_centerlines.csv"

env -u PYTHONPATH -u LD_LIBRARY_PATH PYTHONNOUSERSITE=1 \
    "$FSI_PYTHON" "$CSV_SCRIPT" "$centerline_vtp" "$centerline_csv"

# Map the smoothed local diameter and percentage-based wall thickness to
# the uncapped inner surface for subsequent extrusion or solid-wall steps.
uncapped_vtp="$output_dir/${output_prefix}_uncapped.vtp"
thickness_vtk="$output_dir/${output_prefix}_wall_thickness.vtk"
env -u PYTHONPATH -u LD_LIBRARY_PATH PYTHONNOUSERSITE=1 \
    "$FSI_PYTHON" "$GAUSS_SCRIPT" \
    "$uncapped_vtp" "$centerline_csv" "$thickness_vtk" \
    --gaussian-sigma "$gaussian_sigma" \
    --extrusion-percentage "$extrusion_percentage" \
    --thickness-smoothing-passes "$thickness_smoothing_passes"

# mapExtrudeDistance reads thickMap.vtk from the current OpenFOAM case by
# default and writes the pointScalarField 0/WallThickness for the wall
# extrusion stage.
thick_map="$fluid_case/thickMap.vtk"
mv -f "$thickness_vtk" "$thick_map"
run_step "Mapping wall thickness onto the fluid wall..." "$fluid_case" \
    log.mapExtrudeDistance "$MAP_EXTRUDE_DISTANCE" \
    -maxDistance "$max_mapping_distance"
echo "  Mapped from: $thick_map"
echo "  mapExtrudeDistance log: $fluid_case/log.mapExtrudeDistance"

# Extrude the mapped fluid wall into a separate conformal solid mesh. The
# varExtrudeFunc dictionary reads ../fluidMeshing/0/WallThickness and uses
# the temporary zero-face outerWall patch for the exposed-patch metadata.
solid_case="$output_dir/varExtrudeFunc"
run_step "Extruding the solid wall..." "$solid_case" log.varExtrudeMesh \
    "$VAR_EXTRUDE_MESH"
echo "  varExtrudeMesh log: $solid_case/log.varExtrudeMesh"

# varExtrudeMesh no longer needs the temporary zero-face patch. Running
# createPatch with an empty operation list removes empty patches while
# leaving all non-empty fluid patches unchanged.
fluid_cleanup_dict="$fluid_case/system/removeEmptyPatchesDict"
{
    cat <<'EOF'
FoamFile
{
    format      ascii;
    class       dictionary;
    object      createPatchDict;
}

pointSync false;
patches ();
EOF
} > "$fluid_cleanup_dict"
run_step "Removing the temporary fluid patch..." "$fluid_case" \
    log.removeEmptyPatches "$CREATE_PATCH" -overwrite \
    -dict system/removeEmptyPatchesDict

# On the extruded solid, the old outerWall is the conformal fluid-facing
# surface and the old wall is the exterior surface. Rename both. The inlet
# and auto-named outlets first receive temporary names: createPatch retains
# the old type when source and destination names are identical, whereas a
# new temporary patch reliably receives the requested generic patch type,
# on which the template pins the ends with a fixed displacement.
solid_patch_dict="$solid_case/system/solidCreatePatchDict"
solid_end_dict="$solid_case/system/solidEndPatchDict"
mapfile -t solid_outlet_patch_names < <(
    patch_sizes "$solid_case/constant/polyMesh/boundary" |
        awk '$1 ~ /^outlet/ { print $1 }'
)
{
    cat <<'EOF'
FoamFile
{
    format      ascii;
    class       dictionary;
    object      createPatchDict;
}

pointSync false;

patches
(
    {
        name innerWall;
        patchInfo { type wall; }
        constructFrom patches;
        patches (outerWall);
    }
    {
        name outerWall;
        patchInfo { type wall; }
        constructFrom patches;
        patches (wall);
    }
    {
        name end_inlet_tmp;
        patchInfo { type patch; }
        constructFrom patches;
        patches (inlet);
    }
EOF
    for solid_patch_name in "${solid_outlet_patch_names[@]}"; do
        cat <<EOF
    {
        name end_${solid_patch_name}_tmp;
        patchInfo { type patch; }
        constructFrom patches;
        patches ($solid_patch_name);
    }
EOF
    done
    cat <<'EOF'
);
EOF
} > "$solid_patch_dict"
run_step "Naming the solid patches..." "$solid_case" log.createPatch \
    "$CREATE_PATCH" -overwrite -dict system/solidCreatePatchDict

# Restore the public inlet and auto patch names in a second pass. Their
# source patches are already generic patches, and explicitly repeating the
# type also makes the intended final boundary definition unambiguous.
{
    cat <<'EOF'
FoamFile
{
    format      ascii;
    class       dictionary;
    object      createPatchDict;
}

pointSync false;

patches
(
    {
        name inlet;
        patchInfo { type patch; }
        constructFrom patches;
        patches (end_inlet_tmp);
    }
EOF
    for solid_patch_name in "${solid_outlet_patch_names[@]}"; do
        cat <<EOF
    {
        name $solid_patch_name;
        patchInfo { type patch; }
        constructFrom patches;
        patches (end_${solid_patch_name}_tmp);
    }
EOF
    done
    cat <<'EOF'
);
EOF
} > "$solid_end_dict"
run_step "Setting the solid end patches to patch..." "$solid_case" \
    log.createPatch.ends "$CREATE_PATCH" -overwrite \
    -dict system/solidEndPatchDict

expected_end_count=$((1 + ${#solid_outlet_patch_names[@]}))
verified_end_count="$(awk '
    /^[[:space:]]*[A-Za-z_][A-Za-z0-9_]*[[:space:]]*$/ {
        candidate = $1
    }
    $1 == "type" && (candidate == "inlet" || candidate ~ /^outlet/) {
        type = $2
        sub(/;.*/, "", type)
        if (type != "patch") {
            printf "Error: solid patch %s has type %s, expected patch\n", \
                candidate, type > "/dev/stderr"
            failed = 1
        }
        count++
    }
    END {
        if (failed) exit 1
        print count + 0
    }
' "$solid_case/constant/polyMesh/boundary")" || exit 1
if (( verified_end_count != expected_end_count )); then
    echo "Error: expected $expected_end_count solid end patches of type patch, found $verified_end_count" >&2
    exit 1
fi

echo "Generated solid wall mesh in: $solid_case"
echo "Removed the temporary zero-face outerWall patch from the fluid mesh."
echo "Renamed solid outerWall to innerWall and solid wall to outerWall."
echo "Set the solid inlet and outlet patches to type patch."

# Assemble the coupled FSI run case from the reusable template. The name was
# checked at startup; check again in case another run has since created it.
fluid_poly_mesh="$fluid_case/constant/polyMesh"
solid_poly_mesh="$solid_case/constant/polyMesh"

if [[ ! -d "$fluid_poly_mesh" ]]; then
    echo "Error: generated fluid polyMesh not found: $fluid_poly_mesh" >&2
    exit 1
fi
if [[ ! -d "$solid_poly_mesh" ]]; then
    echo "Error: generated solid polyMesh not found: $solid_poly_mesh" >&2
    exit 1
fi
if [[ -e "$run_case" ]]; then
    echo "Error: run case already exists: $run_case" >&2
    echo "Move or remove it before rerunning meshing.sh." >&2
    exit 1
fi

mkdir -p "$RUN_DIR"
cp -a "$case_template" "$run_case"
cp -a "$fluid_poly_mesh" "$run_case/constant/fluid/"
cp -a "$solid_poly_mesh" "$run_case/constant/solid/"

echo "Created coupled run case in: $run_case"
echo "Copied fluid mesh to: $run_case/constant/fluid/polyMesh"
echo "Copied solid mesh to: $run_case/constant/solid/polyMesh"

# Point the inlet at the waveform for the chosen species.
run_velocity="$run_case/0/fluid/U"
sed -i -E "s#(file[[:space:]]+\"<constant>/fluid/inletFlow/)[A-Za-z]+(\";)#\1$inlet_flow_file\2#" \
    "$run_velocity"
if ! grep -q "<constant>/fluid/inletFlow/$inlet_flow_file\";" "$run_velocity"; then
    echo "Error: could not point the inlet in $run_velocity at $inlet_flow_file" >&2
    exit 1
fi
echo "Inlet flow rate read from: constant/fluid/inletFlow/$inlet_flow_file"

run_control_dict="$run_case/system/controlDict"
sed -i -E "s/^([[:space:]]*endTime[[:space:]]+)[^;]*;/\1$end_time;/" "$run_control_dict"
if ! grep -Eq "^[[:space:]]*endTime[[:space:]]+$end_time;" "$run_control_dict"; then
    echo "Error: could not set endTime in $run_control_dict" >&2
    exit 1
fi
echo "Set endTime to $end_time s ($heartbeats heartbeat(s))"

for decompose_dict in "$run_case"/system/decomposeParDict \
                      "$run_case"/system/{fluid,solid}/decomposeParDict; do
    [[ -f "$decompose_dict" ]] || continue
    sed -i -E "s/^([[:space:]]*numberOfSubdomains[[:space:]]+)[0-9]+;/\1$cores;/" \
        "$decompose_dict"
    if ! grep -Eq "^[[:space:]]*numberOfSubdomains[[:space:]]+$cores;" "$decompose_dict"; then
        echo "Error: could not set numberOfSubdomains in $decompose_dict" >&2
        exit 1
    fi
done
if [[ -f "$run_case/run.slurm" ]]; then
    job_name="$(basename -- "$run_case")"
    sed -i -E -e "s/^(#SBATCH[[:space:]]+--ntasks=)[0-9]+/\1$cores/" \
        -e "s|^(#SBATCH[[:space:]]+--job-name=).*|\1${job_name//|/_}|" \
        "$run_case/run.slurm"
fi
fluid_cells="$(awk '$1 == "cells:" { print $2; exit }' "$fluid_case/log.checkMesh")"
echo "Decomposing both regions into $cores subdomains"
if [[ "$fluid_cells" =~ ^[0-9]+$ ]]; then
    echo "  Fluid cells: $fluid_cells, about $(( (fluid_cells + cores / 2) / cores )) per processor"
else
    echo "  Warning: could not read the fluid cell count from $fluid_case/log.checkMesh" >&2
fi

# Split the Windkessel totals across the outlets by area. The fragment is
# the only definition of the outlet conditions, included by 0/fluid/p.
windkessel_file="$run_case/0/fluid/windkesselOutlets"
echo "Splitting the Windkessel totals across the outlets..."
"$FSI_PYTHON" "$WINDKESSEL_SCRIPT" "$profiles_csv" "$windkessel_file" \
    --proximal-resistance "$wk_proximal_resistance" \
    --distal-resistance "$wk_distal_resistance" \
    --compliance "$wk_compliance" \
    --exponent "$flow_split_exponent" \
    --transport-properties "$run_case/constant/fluid/transportProperties" \
    | tee "$run_case/log.windkesselOutlets"

# Scale only the run-case copies, so the intermediate meshes keep the STL
# units and stay consistent with the thickness map and surfaces beside them.
if awk -v value="$scale_factor" 'BEGIN { exit !(value + 0 != 1) }'; then
    # No log is kept: the output is only shown if transformPoints fails.
    for region in fluid solid; do
        echo "Scaling the $region mesh by $scale_factor..."
        if ! transform_output="$(cd "$run_case" && "$TRANSFORM_POINTS" \
                -region "$region" -scale "$scale_factor" 2>&1)"; then
            printf '%s\n' "$transform_output" >&2
            echo "Error: step failed: scaling the $region mesh" >&2
            exit 1
        fi
    done
    echo "Scaled both run-case meshes by $scale_factor."
else
    echo "Scale factor is 1; run-case meshes left in STL units."
fi

# Record how this case was made, so a result can be traced back to its inputs
# or the case regenerated exactly.
params_file="$run_case/meshing.params"
{
    echo "# Written by meshing.sh on $(date '+%Y-%m-%d %H:%M:%S')"
    printf '# Command:'
    printf ' %q' "$0" "${arguments[@]}"
    printf '\n'
    if commit="$(git -C "$SCRIPT_DIR" rev-parse --short HEAD 2>/dev/null)"; then
        if ! git -C "$SCRIPT_DIR" diff --quiet HEAD -- . 2>/dev/null; then
            commit="$commit (with uncommitted changes)"
        fi
        echo "# Repository commit: $commit"
    fi
    echo
    print_settings
    printf '%-28s %s\n' "Fluid cells:" "${fluid_cells:-unknown}"
} > "$params_file"
echo "Recorded the settings in: $params_file"


# Offer to remove only the intermediate caseFiles directory created for this
# geometry. Never recursively remove a custom --output-dir, since it may also
# contain files that were not generated by this script. Batch runs retain the
# intermediate files because they cannot provide explicit confirmation.
case_files_dir="$SCRIPT_DIR/caseFiles/$case_name"
if [[ -n "$case_name" && "$case_name" != "." && "$case_name" != ".." &&
      "$output_dir" == "$case_files_dir" && -d "$case_files_dir" && -t 0 ]]; then
    read -r -p "Remove the intermediate meshing case '$case_files_dir'? [y/N]: " remove_case
    case "$remove_case" in
        y|Y|yes|YES|Yes)
            rm -rf -- "$case_files_dir"
            echo "Removed intermediate meshing case: $case_files_dir"
            ;;
        *)
            echo "Retained intermediate meshing case: $case_files_dir"
            ;;
    esac
elif [[ "$output_dir" != "$case_files_dir" ]]; then
    echo "Retained custom meshing output directory: $output_dir"
fi

echo
echo "Run case ready: $run_case"
echo "Settings recorded in: $params_file"
echo
echo "Next steps:"
echo "  cd $run_case"
echo "  checkMesh -region solid    # look for self-intersection at the bifurcations"
echo "  sbatch run.slurm"
echo
echo "If the solid self-intersects, rerun with a smaller --extrusion-percentage"
echo "or more smoothing."
